# Form implementation generated from reading ui file 'view/ui/HelpWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets, QtWebEngineWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(488, 429)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/assets/icons/AVEGA-Favicon.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(
            parent=self.centralwidget
        )
        self.webEngineView.setGeometry(QtCore.QRect(40, 40, 401, 341))
        self.webEngineView.setUrl(
            QtCore.QUrl(
                "file:///C:/Users/aster/Documents_/Programming/avega_sampling/LICENSE"
            )
        )
        self.webEngineView.setObjectName("webEngineView")
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AVEGA Random"))
