# Form implementation generated from reading ui file 'view/ui/OutputWindow.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(778, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(
            QtGui.QPixmap(":/assets/icons/AVEGA-Favicon.ico"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.legend_output_wrapper = QtWidgets.QFrame(parent=self.centralwidget)
        self.legend_output_wrapper.setGeometry(QtCore.QRect(10, 10, 761, 41))
        self.legend_output_wrapper.setStyleSheet("")
        self.legend_output_wrapper.setFrameShape(QtWidgets.QFrame.Shape.Panel)
        self.legend_output_wrapper.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.legend_output_wrapper.setObjectName("legend_output_wrapper")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(
            parent=self.legend_output_wrapper
        )
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(10, 10, 731, 28))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.legend_output = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.legend_output.setContentsMargins(0, 0, 0, 0)
        self.legend_output.setObjectName("legend_output")
        self.pushButton_new_file_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_new_file_output.setEnabled(False)
        self.pushButton_new_file_output.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(
            QtGui.QPixmap(":/assets/icons/new_file.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_new_file_output.setIcon(icon1)
        self.pushButton_new_file_output.setAutoDefault(False)
        self.pushButton_new_file_output.setDefault(False)
        self.pushButton_new_file_output.setFlat(False)
        self.pushButton_new_file_output.setObjectName("pushButton_new_file_output")
        self.legend_output.addWidget(self.pushButton_new_file_output)
        self.pushButton_save_as_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_save_as_output.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(
            QtGui.QPixmap(":/assets/icons/folder.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_save_as_output.setIcon(icon2)
        self.pushButton_save_as_output.setObjectName("pushButton_save_as_output")
        self.legend_output.addWidget(self.pushButton_save_as_output)
        self.pushButton_save_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_save_output.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(
            QtGui.QPixmap(":/assets/icons/save.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_save_output.setIcon(icon3)
        self.pushButton_save_output.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_save_output.setObjectName("pushButton_save_output")
        self.legend_output.addWidget(self.pushButton_save_output)
        spacerItem = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.legend_output.addItem(spacerItem)
        self.pushButton_copy_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_copy_output.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(
            QtGui.QPixmap(":/assets/icons/copy.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_copy_output.setIcon(icon4)
        self.pushButton_copy_output.setObjectName("pushButton_copy_output")
        self.legend_output.addWidget(self.pushButton_copy_output)
        self.pushButton_paste_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_paste_output.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(
            QtGui.QPixmap(":/assets/icons/paste.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_paste_output.setIcon(icon5)
        self.pushButton_paste_output.setIconSize(QtCore.QSize(16, 16))
        self.pushButton_paste_output.setObjectName("pushButton_paste_output")
        self.legend_output.addWidget(
            self.pushButton_paste_output, 0, QtCore.Qt.AlignmentFlag.AlignHCenter
        )
        spacerItem1 = QtWidgets.QSpacerItem(
            40,
            20,
            QtWidgets.QSizePolicy.Policy.Expanding,
            QtWidgets.QSizePolicy.Policy.Minimum,
        )
        self.legend_output.addItem(spacerItem1)
        self.pushButton_help_output = QtWidgets.QPushButton(
            parent=self.horizontalLayoutWidget_8
        )
        self.pushButton_help_output.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(
            QtGui.QPixmap(":/assets/icons/q_mark.png"),
            QtGui.QIcon.Mode.Normal,
            QtGui.QIcon.State.Off,
        )
        self.pushButton_help_output.setIcon(icon6)
        self.pushButton_help_output.setObjectName("pushButton_help_output")
        self.legend_output.addWidget(self.pushButton_help_output)
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 60, 781, 20))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.output_element = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.output_element.setGeometry(QtCore.QRect(10, 90, 751, 401))
        self.output_element.setAutoFillBackground(False)
        self.output_element.setReadOnly(True)
        self.output_element.setObjectName("output_element")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AVEGA Random"))
        self.pushButton_new_file_output.setToolTip(_translate("MainWindow", "new file"))
        self.pushButton_save_as_output.setToolTip(_translate("MainWindow", "save as"))
        self.pushButton_save_output.setToolTip(_translate("MainWindow", "save"))
        self.pushButton_copy_output.setToolTip(_translate("MainWindow", "copy"))
        self.pushButton_paste_output.setToolTip(_translate("MainWindow", "paste"))
        self.pushButton_help_output.setToolTip(_translate("MainWindow", "help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
